apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  name: random-hash
  namespace: default
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 5
  parallelism: 2
  suspend: false
  template:
    spec:
      containers:
        - command: ["/bin/sh", "-c", "echo $RANDOM | base64 | head -c 20"]
          image: busybox
          imagePullPolicy: Always
          name: random-hash
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
