--- 
apiVersion: v1
kind: Pod
metadata:
  name: adaptor
spec: 
  containers: 
  - name: app
    image: busybox
    volumeMounts:
      - mountPath: /var/logs
        name: logdir
    command:
      - 'sh'
      - '-c'
      - ' while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep 5; done;'
  - name: transformer
    image: busybox
    volumeMounts:
      - mountPath: /var/logs
        name: logdir
    command: 
      - 'sh'
      - '-c'
      - 'sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;'
  volumes:
    - name: logdir
      emptyDir: {}
