---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv
spec: 
  capacity:
    storage: 512Mi
  # claimRef:
  #   name: pvc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/config
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteMany
  # volumeName: pvc
  storageClassName: ""
  resources:
    requests: 
      storage: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: nginx:1.21.6
      volumeMounts:
        - mountPath: /var/app/config
          name: pvc-config
  volumes:
    - name: pvc-config
      persistentVolumeClaim:
        claimName: pvc



