---
apiVersion: v1
kind: Namespace
metadata:
  name: ext-access
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rate-limiter
  name: rate-limiter
  namespace: ext-access
spec:
  containers:
  - image: bmuschko/nodejs-business-app:1.0.0
    name: business-app
    ports:
    - containerPort: 8080
    resources: {}
  - image: bmuschko/nodejs-ambassador:1.0.0
    name: ambassador
    ports:
    - containerPort: 8081

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
