--- 
apiVersion: v1
kind: Namespace
metadata:
  name: h92
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: h92
spec:
  containers: 
    - name: nginx
      image: nginx:1.21.6
      volumeMounts:
        - mountPath: /var/run
          name: nginx-run
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /usr/local/nginx
          name: nginx-data
  volumes:
    - name: nginx-run
      emptyDir:
        sizeLimit: 500Mi
    - name: nginx-cache
      emptyDir:
        sizeLimit: 500Mi
    - name: nginx-data
      emptyDir:
        sizeLimit: 500Mi
