---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
    team: shiny
  annotations:
    contact: John Doe
    commit: 2d3mg3
  name: frontend
spec:
  containers:
  - image: nginx
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
    team: legacy
    app: v1.2.4
  annotations:
    contact: Mary Harris
  name: backend
spec:
  containers:
  - image: nginx
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod 
    team: storage
  name: database
spec:
  containers:
  - image: nginx
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
